version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: appCarregaBanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: root@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
